In [1]:
import pandas as pd

In [28]:
from google import genai

client = genai.Client(api_key="AIzaSyD35ZNAgfIuYxaNKDmmPAqaG8dpfsRQbEA")

response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents="Explain how AI works",
)

print(response.text)

Okay, let's break down how AI works, trying to avoid jargon as much as possible and focusing on the core concepts.

**In Essence: Learning from Data to Make Decisions**

At its heart, AI is about creating machines that can perform tasks that typically require human intelligence. This includes things like:

*   **Learning:** Acquiring information and rules for using the information.
*   **Reasoning:** Applying rules and logic to reach conclusions.
*   **Problem Solving:** Identifying and implementing steps to achieve goals.
*   **Perception:** Understanding sensory data (like images, sound, text).
*   **Natural Language Processing (NLP):** Understanding and generating human language.

To achieve these abilities, AI systems use algorithms (sets of instructions) to analyze large amounts of data, identify patterns, and then use those patterns to make predictions, decisions, or take actions.

**Key Concepts and Components**

1.  **Data:**

    *   AI thrives on data. The more data an AI system has to learn from, the better it can perform.
    *   Data can be in various forms:
        *   **Structured Data:** Organized in tables (like spreadsheets or databases).  Examples: customer data, sales figures, sensor readings.
        *   **Unstructured Data:** Not neatly organized. Examples: text documents, images, audio recordings, video files.
    *   Data needs to be preprocessed to be useful, cleaned up from errors and organized.

2.  **Algorithms:**

    *   Algorithms are the sets of rules and instructions that tell an AI system how to process data and learn from it.
    *   Different types of algorithms are used for different tasks. Here are some of the most common:

        *   **Machine Learning (ML) Algorithms:**
            *   These algorithms allow AI systems to learn from data *without* being explicitly programmed for every possible scenario.
            *   **Types of Machine Learning:**
                *   **Supervised Learning:**  The algorithm is trained on a labeled dataset.  "Labeled" means each piece of data has a known answer.  For example:  Training a system to recognize cats in images by showing it many images labeled "cat" or "not cat."  It learns to associate features (like pointy ears, whiskers) with the "cat" label.
                *   **Unsupervised Learning:** The algorithm is trained on an unlabeled dataset. It must discover patterns and relationships in the data on its own.  Examples:  clustering customers into groups based on their purchasing behavior, or detecting anomalies in network traffic.
                *   **Reinforcement Learning:** The algorithm learns by trial and error in an environment.  It receives rewards or penalties for its actions and learns to maximize the rewards.  Examples:  training a robot to walk, or creating an AI to play a game like Go.

        *   **Deep Learning (DL) Algorithms:**
            *   A subfield of machine learning that uses artificial neural networks with many layers (hence "deep").
            *   Neural networks are inspired by the structure of the human brain.  They consist of interconnected nodes (neurons) that process information.
            *   Deep learning is particularly good at handling complex, unstructured data like images, audio, and text.
            *   Example: Image recognition (identifying objects in pictures), natural language processing (understanding and generating text), speech recognition.

        *   **Rule-Based Systems:**
            *   These systems use a set of predefined rules to make decisions.  The rules are typically created by human experts.
            *   Example:  A medical diagnosis system that uses rules to determine the likelihood of a disease based on a patient's symptoms.

3.  **Models:**

    *   A model is the output of an AI algorithm after it has been trained on data.
    *   It represents the learned patterns and relationships from the data.
    *   The model can then be used to make predictions or decisions on new, unseen data.
    *   Think of the model as a recipe that the AI system uses.  The more the recipe is perfected and refined, the better the model will be.

4.  **Training:**

    *   The process of feeding data to an AI algorithm and allowing it to learn.
    *   During training, the algorithm adjusts its internal parameters (weights and biases in neural networks, for example) to improve its performance.
    *   The goal of training is to create a model that is accurate and can generalize well to new data.

5.  **Inference:**

    *   The process of using a trained model to make predictions or decisions on new data.
    *   The model takes the new data as input and produces an output (e.g., a prediction, a classification, or an action).

**Simplified Examples**

*   **Spam Filter (Supervised Learning):**
    *   **Data:** A large collection of emails, labeled as "spam" or "not spam."
    *   **Algorithm:** A supervised learning algorithm (e.g., a Naive Bayes classifier)
    *   **Training:** The algorithm learns which words and phrases are most commonly associated with spam emails.
    *   **Model:** The trained model is a set of rules that can be used to classify new emails as spam or not spam.
    *   **Inference:** When a new email arrives, the model analyzes the email and predicts whether it is spam.

*   **Image Recognition (Deep Learning):**
    *   **Data:** A massive dataset of images, each labeled with the object it contains (e.g., "cat," "dog," "car").
    *   **Algorithm:** A deep learning algorithm (e.g., a convolutional neural network - CNN).
    *   **Training:** The CNN learns to identify patterns and features in the images that are associated with different objects.
    *   **Model:** The trained model is a complex neural network that can recognize objects in new images.
    *   **Inference:**  The model analyzes a new image and identifies the objects it contains.

**Types of AI**

*   **Narrow or Weak AI:** Designed for a specific task. Most of the AI we see today falls into this category. Examples:  Siri, Alexa, spam filters, recommendation systems.
*   **General or Strong AI:** Has human-level intelligence and can perform any intellectual task that a human being can. This is still largely theoretical.
*   **Super AI:**  Exceeds human intelligence in all aspects. This is also largely theoretical and raises many ethical concerns.

**Challenges and Considerations**

*   **Bias:** AI systems can inherit biases from the data they are trained on. This can lead to unfair or discriminatory outcomes.
*   **Explainability:** Some AI models, especially deep learning models, are difficult to understand. This can make it hard to trust their decisions. This is often called the "black box" problem.
*   **Data Privacy:** AI systems often require large amounts of data, which can raise concerns about data privacy and security.
*   **Ethical Considerations:**  AI raises a number of ethical questions, such as: How should AI be used in warfare?  How do we ensure that AI is used for good and not for harm?

**In Summary**

AI works by using algorithms to analyze data, identify patterns, and make predictions or decisions. The type of algorithm used depends on the task at hand and the type of data available. AI is a rapidly evolving field with the potential to transform many aspects of our lives.  It is important to understand how AI works and its potential implications in order to use it responsibly.

# Woking with JSON

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

```
Reading json from url
```

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,0.0422
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,0.8370
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,1.0700
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,4.5300
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,1.2800
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,2.8400
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,0.2120
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,0.3300
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-03-06,1741219201,0.3060

# Working with SQL

In [ ]:
pip install sqlalchemy
pip install pymysql

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 693.4 kB/s eta 0:00:17
     - ------------------------------------- 0.5/11.9 MB 693.4 kB/s eta 0:00:17
     -- ------------------------------------ 0.8/11.9 MB 751.9 kB/s eta 0:00:15
     ---- ----------------------------------- 1.3/11.9 MB 1.1 MB/s eta 0:00:10
     ----- ---------------------------------- 1.6/11.9 MB 1.1 MB/s eta 0:00:10
     ------- -------------------------------- 2.1/11.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 2.9/11.9 MB 1.6 MB/s eta 0:00:06
     ----------- ---------------------------- 3.4/11.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.9 MB 2.1 MB/s eta 0:00:04
     ------------------ --------------------- 5.5/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.0/11.9 MB 2.4 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.4 MB/s eta 0:00:03
     --------------------------- ------------ 8.1/11.9 MB 2.8 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.8 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.8 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 3.0 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248022 sha256=f56ff07572ab2d1d1da51dbb56a2d1d3b4d97913bc90b15c8e712234ed95d78a
  Stored in directory: c:\users\panth\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [19]:
from sqlalchemy import create_engine

In [23]:
engine = create_engine('mysql+pymysql://root:@localhost/world')

In [25]:
df = pd.read_sql_query("SELECT * FROM country", engine)

In [26]:
df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW